#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Nov 20 11:24:46 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_Sub_Abber_behav -key {Behavioral:sim_1:Functional:tb_Sub_Abber} -tclbatch tb_Sub_Abber.tcl -view /home/it/01Design_repo/lab02/Tas3_lab2/tb_Sub_Abber_behav.wcfg -log simulate.log"
xsim tb_Sub_Abber_behav -key {Behavioral:sim_1:Functional:tb_Sub_Abber} -tclbatch tb_Sub_Abber.tcl -view /home/it/01Design_repo/lab02/Tas3_lab2/tb_Sub_Abber_behav.wcfg -log simulate.log

